### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by PoseidonMRT** [kituri/Demo-Retrofit-MVP#1]
建议新建RetrofitFactory，泛型构造Retrofit，避免每个API都要写一个对应的XXXRetrofit，更好的面向更改

**Comment by kituri** [comment]
感谢建议，其实后续已经有更新Factory版本，我犯懒没更新上去，实在是有点抱歉，这就更新上去，感谢支持建议~thx

**Comment by kituri** [comment]
已更新

**Comment by PoseidonMRT** [comment]
嗯嗯，虽然是demo，但是还是要尽可能的多考虑一点，麻雀虽小，五脏俱全，嘿嘿，我也是菜，不过我处理的是dagger2+retrofit2+okhttp+butterknife+mvp+rxjava的一个demo，看到你有写，就顺手提了一下issume，嘿嘿
